import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/ui/Sidebar/Sidebar";
import { Noto_Sans_Thai } from "next/font/google";
import Header from "@/components/ui/Header/Header";

const fontThai = Noto_Sans_Thai({
  subsets: ["thai"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontThai.variable} font-sans antialiased flex items-start justify-between bg-[#F7F7F7]`}>
        <Sidebar />
        <main className="grid w-full h-full pl-[300px] ">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
