import { readFileSync, writeFileSync } from "node:fs"
import { spawnSync } from "node:child_process"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const sqliteSchemaPath = join(root, "prisma", "schema.prisma")
const postgresSchemaPath = join(root, "prisma", "schema.postgresql.prisma")
const prismaExecutable = join(
  root,
  "node_modules",
  ".bin",
  process.platform === "win32" ? "prisma.cmd" : "prisma",
)

function createPostgresSchema() {
  const source = readFileSync(sqliteSchemaPath, "utf8")
  const datasource = [
    "datasource db {",
    '  provider  = "postgresql"',
    '  url       = env("DATABASE_URL")',
    '  directUrl = env("DIRECT_URL")',
    "}",
  ].join("\n")
  const transformed = source.replace(/datasource db \{[\s\S]*?\n\}/, datasource)

  if (transformed === source) {
    throw new Error("Could not locate the Prisma datasource block")
  }

  writeFileSync(
    postgresSchemaPath,
    [
      "// Generated from prisma/schema.prisma by scripts/prisma-schema.mjs.",
      "// Do not edit this file directly.",
      transformed,
    ].join("\n"),
  )

  return postgresSchemaPath
}

function runPrisma(args) {
  const result = spawnSync(prismaExecutable, args, {
    cwd: root,
    env: process.env,
    stdio: "inherit",
  })

  if (result.error) throw result.error
  if (result.status !== 0) process.exit(result.status ?? 1)
}

const [mode, ...args] = process.argv.slice(2)

if (mode === "generate") {
  const usePostgres = /^postgres(?:ql)?:\/\//i.test(process.env.DATABASE_URL ?? "")
  runPrisma(["generate", "--schema", usePostgres ? createPostgresSchema() : sqliteSchemaPath])
} else if (mode === "sqlite") {
  if (args.length === 0) throw new Error("Missing Prisma command")
  runPrisma([...args, "--schema", sqliteSchemaPath])
} else if (mode === "postgres") {
  if (args.length === 0) throw new Error("Missing Prisma command")
  const schemaPath = createPostgresSchema()
  const isMigrationDiff = args[0] === "migrate" && args[1] === "diff"
  runPrisma(isMigrationDiff ? args : [...args, "--schema", schemaPath])
} else {
  throw new Error('Usage: prisma-schema.mjs "generate", "sqlite <prisma command...>", or "postgres <prisma command...>"')
}
